### ISSUE TITLE
Implement command line arguments parsing

### ISSUE THREAD

**Issue by juzam** [initbrain/Python-Wi-Fi-Positioning-System#1]
Investigate how to properly parse command line arguments (argparse module?) with at least:

* -h help
* -i wifi_interface to specify which interface to use subsequently

**Comment by juzam** [comment]
https://github.com/initbrain/Python-Wi-Fi-Positioning-System/commit/9c4f26771d0b58b9bbb05a2cd1a19e1bf71a8ae8 implements most of the command line arguments except --json-prettify

**Comment by initbrain** [comment]
https://github.com/initbrain/Python-Wi-Fi-Positioning-System/commit/88d70f684249504ac055b9be5297392f702beb1e implements these command line arguments :
- -V, --version : show program's version number and exit
- -L, --license : show program's license details and exit
- -p, --json-prettify : prettify JSON output
- -k API_KEY, --api-key API_KEY : Google Maps Geolocation API key (could be hardcoded)

And :
- display the usage in case or argument error ;
- automatically remove required arguments in case of Mac OS X usage.

**Comment by juzam** [comment]
* non prettified JSON is currently broken.  https://github.com/initbrain/Python-Wi-Fi-Positioning-System/pull/6 addresses it.

**Comment by initbrain** [comment]
Thanks =D
