### ISSUE TITLE
Broken when run as a non privileged user

### ISSUE THREAD

**Issue by juzam** [initbrain/Python-Wi-Fi-Positioning-System#7]
running on linux as a non privileged user is currently broken. https://github.com/initbrain/Python-Wi-Fi-Positioning-System/pull/6 addresses it.

(tested on Raspbian)

**Comment by initbrain** [comment]
Patched in https://github.com/initbrain/Python-Wi-Fi-Positioning-System/commit/58273c00bbff5ba1773f9261c7642f2957c5f63e, let me know if this is ok with your Raspbian

**Comment by juzam** [comment]
almost! ;) this one was tricky to track down. It's basically ok if you don't define the API key via Environment variables. That's because sudo don't preserve the Env by default, addressed by https://github.com/initbrain/Python-Wi-Fi-Positioning-System/pull/8

( I chose to use `--preserve-env` instead of `-E` for clarity)

**Comment by initbrain** [comment]
Perfect, I'll look at the others soon
